name: CI Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - Manual
env:
  SONAR_TOKEN: '75621cba6337eff300a0b42e8d68eb9d4cdbe709'
  SONAR_HOST_URL: 'http://brillioonesonar.eastus.cloudapp.azure.com:9000'
  
jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        
      - name: Run Tests
        run: mvn test
        
      - name: Publish Artifact to JFrog Artifactory
        run: |
          # Configure JFrog Artifactory details
          export ARTIFACTORY_URL='https://jcenter.bintray.com'
          export ARTIFACTORY_REPO='demo1-genai'
          export ARTIFACTORY_USERNAME='Vishwa'
          export ARTIFACTORY_PASSWORD='JE2cwqvRNdJRPWKg1gF1iPhepdJx9FEqU8oz4coS9pYAFo7HYm'
          
          # Install JFrog CLI
          curl -fL https://getcli.jfrog.io | sh
          
          sleep 1
          
          # Upload JAR artifact to Artifactory
          ./jfrog rt u ./target/*.jar $ARTIFACTORY_REPO/ --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_PASSWORD

  sonarqube:
    name: SonarQube Analysis
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.2.0
        with:
          SONAR_TOKEN: ${{env.SONAR_TOKEN }}
          projectKey: ${{ env.sonar.projectKey }}
          projectName: ${{ env.sonar.projectName }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
